# Generated by Django 3.2.16 on 2026-04-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20260402_1623"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
